## **Exercise 4.01:** 
### Building a Model for Classifying Glass Type and Assessing Its Performance

### Import the pandas package:

In [59]:
import pandas as pd
import numpy as np

### Loading the "glass" data:

In [60]:
glass_data = pd.read_csv\
('https://raw.githubusercontent.com/fenago/DSBook/main/Chapter%204/glass.csv')

glass_data.head()

        RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

### Extracting the 'Type' column using the .pop() method from pandas to predict the type of glass:

In [62]:
# Type your code here:



# ---Solution ---#
#target = glass_data.pop('Type')
#glass_data.head()

        RI     Na    Mg    Al     Si     K    Ca   Ba   Fe
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0

### Importing the train_test_split function from sklearn.model_selection

In [74]:
from sklearn.model_selection import train_test_split

#### Splitting the dataset into training and testing sets with the df, y, test_size=0.4, and random_state=188 parameters

In [ ]:
# ---- type your code here ---#



# --- Solution --- #
#X_train, X_test, y_train, y_test = train_test_split\
#                                  (glass_data, target, test_size=0.4, \
#                                   random_state=188)

### Import RandomForestClassifier from sklearn.ensemble:

In [66]:
from sklearn.ensemble import RandomForestClassifier

f_model = RandomForestClassifier(random_state=80, \
                                  n_estimators=10)

###  Fitting RandomForestClassifier with the training set

In [67]:
f_model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=10, random_state=80)

### Predicting the outcome of the training set with the .predict()method,

In [69]:
# ---- type your code here ---#



# --- Solution --- #
#train_preds = f_model.predict(X_train)
#train_preds

array([2, 1, 2, 7, 7, 1, 2, 2, 3, 7, 1, 2, 2, 2, 1, 7, 2, 7, 1, 2, 1, 7,
       2, 1, 1, 7, 2, 6, 7, 3, 2, 2, 3, 2, 2, 7, 7, 1, 2, 2, 7, 6, 2, 7,
       2, 1, 2, 2, 2, 1, 1, 5, 2, 2, 2, 2, 1, 1, 5, 7, 2, 2, 2, 1, 5, 6,
       5, 2, 2, 7, 1, 1, 2, 5, 3, 7, 3, 7, 6, 7, 1, 6, 3, 1, 1, 2, 7, 2,
       1, 2, 1, 1, 3, 7, 1, 6, 2, 2, 7, 1, 7, 7, 6, 1, 1, 1, 5, 7, 2, 1,
       1, 5, 2, 2, 2, 7, 2, 2, 2, 1, 3, 2, 1, 1, 1, 5, 7, 5])

###  Importing the accuracy_score function from sklearn.metrics:

In [70]:
from sklearn.metrics import accuracy_score

### Calculate the accuracy score on the training set, save the result in a variable called train_acc, and print its value:

In [71]:
train_acc = accuracy_score(y_train, train_preds)
print(train_acc)

1.0

### Predicting the outcome of the testing set with the .predict() method

In [72]:
test_preds = f_model.predict(X_test)

In [73]:
test_acc = accuracy_score(y_test, test_preds)
print(test_acc)

0.7790697674418605