## **Practice Exercise 4.04**: 
###  Tuning min_samples_leaf

### Importing modules

In [ ]:
import pandas as pd
import numpy as np

### Loading data

In [ ]:
animals_data = pd.read_csv\
('https://raw.githubusercontent.com/fenago/DSBook/main/Chapter%204/zoo2.csv')

glass_data.head()

        RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

### Remove the Type column using .drop() and then extract the Type targetvariable

In [ ]:
# Type your code here:

        RI     Na    Mg    Al     Si     K    Ca   Ba   Fe
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0

In [ ]:
from sklearn.model_selection import train_test_split

### Instantiate RandomForestClassifier with random_state=42 and n_estimators=30, max_depth=2,  min_samples_leaf=7, and then fit the model with the training set:

RandomForestClassifier(max_depth=2, min_samples_leaf=3, n_estimators=30,
                       random_state=42)

### Make predictions on the training and testing sets with .predict()

### Print the accuracy scores: train_acc and test_acc:

0.6953125
0.5930232558139535

### Instantiating another RandomForestClassifier  with random_state=42, n_estimators=30, and max_depth=2, and  min_samples_leaf=7

RandomForestClassifier(max_depth=2, min_samples_leaf=7, n_estimators=30,
                       random_state=42)

### Make predictions on the training and testing sets with .predict()

### Calculating the accuracy score for the training and testing sets a

###  Printing the accuracy scores: train_acc and test_acc:

0.6640625
0.5581395348837209