## **Practice Exercise 4.01**: 
###  Tuning max_features

### Importing modules

In [1]:
import pandas as pd
import numpy as np

### Loading data

In [2]:
glass_data = pd.read_csv\
('https://raw.githubusercontent.com/fenago/DSBook/main/Chapter%204/zoo2.csv')

glass_data.head()

,animal_name,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,class_type
0,turtle,0,0,1,0,0,1,0,0,1,1,0,0,4,1,1,1,3
1,chameleon,0,0,1,0,0,0,0,1,1,1,0,0,4,1,1,0,3
2,iguana,0,0,1,0,0,0,1,1,1,1,0,0,4,1,1,1,3
3,lizard,0,0,1,0,0,0,1,1,1,1,0,0,4,1,0,0,3
4,gecko,0,0,1,0,0,0,0,1,1,1,0,0,4,1,1,0,3

### Remove the Type column using .drop() and then extract the Type targetvariable

,animal_name,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize
0,turtle,0,0,1,0,0,1,0,0,1,1,0,0,4,1,1,1
1,chameleon,0,0,1,0,0,0,0,1,1,1,0,0,4,1,1,0
2,iguana,0,0,1,0,0,0,1,1,1,1,0,0,4,1,1,1
3,lizard,0,0,1,0,0,0,1,1,1,1,0,0,4,1,0,0
4,gecko,0,0,1,0,0,0,0,1,1,1,0,0,4,1,1,0

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
# ---- type your code here ---#

### Instantiate RandomForestClassifier with random_state=42 and n_estimators=10, and then fit the model with the training set: