## **Activity 2.02:**
### Fitting a Multi-Log Linear regression model:

### Importing Modules

In [1]:
import statsmodels.formula.api as smf
import pandas as pd
from sklearn.model_selection import train_test_split

%matplotlib inline
import matplotlib as mpl
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
import statsmodels.graphics.api as smg
import numpy as np
import patsy
from statsmodels.graphics.correlation import plot_corr
from sklearn.model_selection import train_test_split
plt.style.use('seaborn')

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

### Loading data

In [2]:
miami_data = pd.read_csv\
('https://raw.githubusercontent.com/fenago/DSBook/main/miami-housing.csv')
miami_data.head()

,LATITUDE,LONGITUDE,PARCELNO,SALE_PRC,LND_SQFOOT,TOT_LVG_AREA,SPEC_FEAT_VAL,RAIL_DIST,OCEAN_DIST,WATER_DIST,CNTR_DIST,SUBCNTR_DI,HWY_DIST,age,avno60plus,month_sold,structure_quality
0,25.891031,-80.160561,622280070620,440000.0,9375,1753,0,2815.9,12811.4,347.6,42815.3,37742.2,15954.9,67,0,8,4
1,25.891324,-80.153968,622280100460,349000.0,9375,1715,0,4359.1,10648.4,337.8,43504.9,37340.5,18125.0,63,0,9,4
2,25.891334,-80.153740,622280100470,800000.0,9375,2276,49206,4412.9,10574.1,297.1,43530.4,37328.7,18200.5,61,0,2,4
3,25.891765,-80.152657,622280100530,988000.0,12450,2058,10033,4585.0,10156.5,0.0,43797.5,37423.2,18514.4,63,0,9,4
4,25.891825,-80.154639,622280100200,755000.0,12800,1684,16681,4063.4,10836.8,326.6,43599.7,37550.8,17903.4,42,0,7,4

### Checking for missing values

In [3]:
raw_data = miami_data.dropna()

In [4]:
raw_data = raw_data.drop_duplicates()

In [5]:
renamedMiamiData = raw_data.rename\
(columns = {\
'LATITUDE':'LATITUDE',\
' LONGITUDE ':'lONGITUDE',\
'PARCELNO ':'Parcel Number',\
'SALE_PRC':'SalePrice',\
'LND_SQFOOT':'LandLength'})
renamedMiamiData.head()

,LATITUDE,LONGITUDE,PARCELNO,SalePrice,LandLength,TOT_LVG_AREA,SPEC_FEAT_VAL,RAIL_DIST,OCEAN_DIST,WATER_DIST,CNTR_DIST,SUBCNTR_DI,HWY_DIST,age,avno60plus,month_sold,structure_quality
0,25.891031,-80.160561,622280070620,440000.0,9375,1753,0,2815.9,12811.4,347.6,42815.3,37742.2,15954.9,67,0,8,4
1,25.891324,-80.153968,622280100460,349000.0,9375,1715,0,4359.1,10648.4,337.8,43504.9,37340.5,18125.0,63,0,9,4
2,25.891334,-80.153740,622280100470,800000.0,9375,2276,49206,4412.9,10574.1,297.1,43530.4,37328.7,18200.5,61,0,2,4
3,25.891765,-80.152657,622280100530,988000.0,12450,2058,10033,4585.0,10156.5,0.0,43797.5,37423.2,18514.4,63,0,9,4
4,25.891825,-80.154639,622280100200,755000.0,12800,1684,16681,4063.4,10836.8,326.6,43599.7,37550.8,17903.4,42,0,7,4

### Divide the DataFrame into training and test sets

In [6]:
X = renamedMiamiData.drop('SalePrice', axis = 1)
y = renamedMiamiData[['SalePrice']]
seed = 10
test_data_size = 0.3
X_train, X_test, \
y_train, y_test = train_test_split(X, y, \
test_size = test_data_size, \
random_state = seed)
train_data = pd.concat([X_train, y_train], axis = 1)
test_data = pd.concat([X_test, y_test], axis = 1)

### Defining a Multiplie Log Linear relationship model

In [7]:
#----Write your code here----#



#-------Solution:---------#
multiLogLinearModel = smf.ols\
                 (formula = 'np.log(SalePrice) ~ (PARCELNO\
                  + WATER_DIST + LandLength + RAIL_DIST)**2', \
data=train_data)

### Fitting the above model:

In [8]:
FinalmultiLogLinearModel = multiLogLinearModel.fit()

In [10]:
print(FinalmultiLogLinearModel.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      np.log(SalePrice)   R-squared:                     -11.348
Model:                            OLS   Adj. R-squared:                -11.359
Method:                 Least Squares   F-statistic:                    -994.8
Date:                Thu, 17 Mar 2022   Prob (F-statistic):               1.00
Time:                        03:39:35   Log-Likelihood:                -20635.
No. Observations:                9752   AIC:                         4.129e+04
Df Residuals:                    9742   BIC:                         4.136e+04
Df Model:                           9
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept              1.046e-07   5.12e-10    204.332      0.000    1.04e-07    1.06e-07
PARCELNO               3.812e-12   3.15e-14    120.871      0.000    3.75e-12    3.87e-12
WATER_DIST                0.0002   9.29e-06     25.817      0.000       0.000       0.000
LandLength                0.0011   7.38e-06    146.147      0.000       0.001       0.001
RAIL_DIST                 0.0004   1.02e-05     40.120      0.000       0.000       0.000
PARCELNO:WATER_DIST   -6.773e-17   2.87e-18    -23.583      0.000   -7.34e-17   -6.21e-17
PARCELNO:LandLength   -3.255e-16   3.46e-18    -94.107      0.000   -3.32e-16   -3.19e-16
PARCELNO:RAIL_DIST     -8.93e-17   3.39e-18    -26.307      0.000    -9.6e-17   -8.26e-17
WATER_DIST:LandLength  4.203e-10   3.51e-10      1.196      0.232   -2.68e-10    1.11e-09
WATER_DIST:RAIL_DIST  -3.697e-09   3.19e-10    -11.572      0.000   -4.32e-09   -3.07e-09
LandLength:RAIL_DIST  -1.333e-08   6.77e-10    -19.677      0.000   -1.47e-08    -1.2e-08
==============================================================================
Omnibus:                     3688.339   Durbin-Watson:                   1.948
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           156727.189
Skew:                          -1.099   Prob(JB):                         0.00
Kurtosis:                      22.516   Cond. No.                     3.55e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.55e+17. This might indicate that there are
strong multicollinearity or other numerical problems.