**Exercise 2.05:**

Fitting a Multiple Linear Regression Model using the StatsModels Formula API:

In [ ]:
import statsmodels.formula.api as smf
import pandas as pd
from sklearn.model_selection import train_test_split

%matplotlib inline
import matplotlib as mpl
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
import statsmodels.graphics.api as smg
import numpy as np
import patsy
from statsmodels.graphics.correlation import plot_corr
from sklearn.model_selection import train_test_split
plt.style.use('seaborn')

LOADING MIAMI_HOUSING DATASET AND DISPLAYING FIRST 5 ENTRIES

In [ ]:
miami_data = pd.read_csv\
('https://raw.githubusercontent.com/fenago/DSBook/main/miami-housing.csv')
miami_data.head()

,LATITUDE,LONGITUDE,PARCELNO,SALE_PRC,LND_SQFOOT,TOT_LVG_AREA,SPEC_FEAT_VAL,RAIL_DIST,OCEAN_DIST,WATER_DIST,CNTR_DIST,SUBCNTR_DI,HWY_DIST,age,avno60plus,month_sold,structure_quality
0,25.891031,-80.160561,622280070620,440000.0,9375,1753,0,2815.9,12811.4,347.6,42815.3,37742.2,15954.9,67,0,8,4
1,25.891324,-80.153968,622280100460,349000.0,9375,1715,0,4359.1,10648.4,337.8,43504.9,37340.5,18125.0,63,0,9,4
2,25.891334,-80.153740,622280100470,800000.0,9375,2276,49206,4412.9,10574.1,297.1,43530.4,37328.7,18200.5,61,0,2,4
3,25.891765,-80.152657,622280100530,988000.0,12450,2058,10033,4585.0,10156.5,0.0,43797.5,37423.2,18514.4,63,0,9,4
4,25.891825,-80.154639,622280100200,755000.0,12800,1684,16681,4063.4,10836.8,326.6,43599.7,37550.8,17903.4,42,0,7,4

In [ ]:
raw_data = miami_data.dropna()

In [ ]:
raw_data = raw_data.drop_duplicates()

Listing the column names of the DataFrame

In [ ]:
list(raw_data.columns)

['LATITUDE',
 'LONGITUDE',
 'PARCELNO',
 'SALE_PRC',
 'LND_SQFOOT',
 'TOT_LVG_AREA',
 'SPEC_FEAT_VAL',
 'RAIL_DIST',
 'OCEAN_DIST',
 'WATER_DIST',
 'CNTR_DIST',
 'SUBCNTR_DI',
 'HWY_DIST',
 'age',
 'avno60plus',
 'month_sold',
 'structure_quality']

Renaming the DataFrame columns from 1 to 5, others are kept same

In [ ]:
renamedMiamiData = raw_data.rename\
(columns = {\
'LATITUDE':'LATITUDE',\
' LONGITUDE ':'lONGITUDE',\
'PARCELNO ':'Parcel Number',\
'SALE_PRC':'SalePrice',\
'LND_SQFOOT':'LandLength'})
renamedMiamiData.head()

,LATITUDE,LONGITUDE,PARCELNO,SalePrice,LandLength,TOT_LVG_AREA,SPEC_FEAT_VAL,RAIL_DIST,OCEAN_DIST,WATER_DIST,CNTR_DIST,SUBCNTR_DI,HWY_DIST,age,avno60plus,month_sold,structure_quality
0,25.891031,-80.160561,622280070620,440000.0,9375,1753,0,2815.9,12811.4,347.6,42815.3,37742.2,15954.9,67,0,8,4
1,25.891324,-80.153968,622280100460,349000.0,9375,1715,0,4359.1,10648.4,337.8,43504.9,37340.5,18125.0,63,0,9,4
2,25.891334,-80.153740,622280100470,800000.0,9375,2276,49206,4412.9,10574.1,297.1,43530.4,37328.7,18200.5,61,0,2,4
3,25.891765,-80.152657,622280100530,988000.0,12450,2058,10033,4585.0,10156.5,0.0,43797.5,37423.2,18514.4,63,0,9,4
4,25.891825,-80.154639,622280100200,755000.0,12800,1684,16681,4063.4,10836.8,326.6,43599.7,37550.8,17903.4,42,0,7,4

In [ ]:
renamedMiamiData.describe(include=[np.number]).T

,count,mean,std,min,25%,50%,75%,max
LATITUDE,13932.0,2.572881e+01,1.406333e-01,2.543433e+01,2.562006e+01,2.573181e+01,2.585227e+01,2.597438e+01
LONGITUDE,13932.0,-8.032748e+01,8.919907e-02,-8.054217e+01,-8.040328e+01,-8.033891e+01,-8.025802e+01,-8.011975e+01
PARCELNO,13932.0,2.356496e+12,1.199290e+12,1.020008e+11,1.079160e+12,3.040300e+12,3.060170e+12,3.660170e+12
SalePrice,13932.0,3.999419e+05,3.172147e+05,7.200000e+04,2.350000e+05,3.100000e+05,4.280000e+05,2.650000e+06
LandLength,13932.0,8.620880e+03,6.070089e+03,1.248000e+03,5.400000e+03,7.500000e+03,9.126250e+03,5.706400e+04
TOT_LVG_AREA,13932.0,2.058045e+03,8.135385e+02,8.540000e+02,1.470000e+03,1.877500e+03,2.471000e+03,6.287000e+03
SPEC_FEAT_VAL,13932.0,9.562493e+03,1.389097e+04,0.000000e+00,8.100000e+02,2.765500e+03,1.235225e+04,1.750200e+05
RAIL_DIST,13932.0,8.348549e+03,6.178027e+03,1.050000e+01,3.299450e+03,7.106300e+03,1.210260e+04,2.962150e+04
OCEAN_DIST,13932.0,3.169099e+04,1.759508e+04,2.361000e+02,1.807935e+04,2.854175e+04,4.431065e+04,7.574490e+04
WATER_DIST,13932.0,1.196029e+04,1.193299e+04,0.000000e+00,2.675850e+03,6.922600e+03,1.920000e+04,5.039980e+04
CNTR_DIST,13932.0,6.849033e+04,3.200847e+04,3.825600e+03,4.282310e+04,6.585240e+04,8.935832e+04,1.599765e+05
SUBCNTR_DI,13932.0,4.111505e+04,2.216183e+04,1.462800e+03,2.399625e+04,4.110990e+04,5.394938e+04,1.105538e+05
HWY_DIST,13932.0,7.723771e+03,6.068936e+03,9.020000e+01,2.998125e+03,6.159750e+03,1.085420e+04,4.816730e+04
age,13932.0,3.066925e+01,2.115307e+01,0.000000e+00,1.400000e+01,2.600000e+01,4.600000e+01,9.600000e+01
avno60plus,13932.0,1.492966e-02,1.212758e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
month_sold,13932.0,6.655828e+00,3.301523e+00,1.000000e+00,4.000000e+00,7.000000e+00,9.000000e+00,1.200000e+01
structure_quality,13932.0,3.513997e+00,1.097444e+00,1.000000e+00,2.000000e+00,4.000000e+00,4.000000e+00,5.000000e+00

Divide the DataFrame into training and test sets

In [ ]:
X = renamedMiamiData.drop('SalePrice', axis = 1)
y = renamedMiamiData[['SalePrice']]
seed = 10
test_data_size = 0.3
X_train, X_test, \
y_train, y_test = train_test_split(X, y, \
test_size = test_data_size, \
random_state = seed)
train_data = pd.concat([X_train, y_train], axis = 1)
test_data = pd.concat([X_test, y_test], axis = 1)

Using the + operator of Patsy formula language to define a linear regression model for SalePrice (dependent Variable) on PARCELNO,WATER_DIST,LandLength,RAIL_DIST (independent Variables).

In [ ]:
#----Write your code here----#



#-------Solution:---------#
#multiLinearModel = smf.ols\
#                 (formula = 'SalePrice ~ PARCELNO \
#+ WATER_DIST \
#+ LandLength \
#+ RAIL_DIST', \
#data=train_data)

Fit method of the model instance:

In [ ]:
FinalmultiLinearModel = multiLinearModel.fit()

Printing the summary of multi Regression model

In [ ]:
print(FinalmultiLinearModel.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.192
Model:                            OLS   Adj. R-squared:                  0.192
Method:                 Least Squares   F-statistic:                     580.1
Date:                Fri, 04 Mar 2022   Prob (F-statistic):               0.00
Time:                        13:45:57   Log-Likelihood:            -1.3648e+05
No. Observations:                9752   AIC:                         2.730e+05
Df Residuals:                    9747   BIC:                         2.730e+05
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   3.692e+05   8182.941     45.117      0.000    3.53e+05    3.85e+05
PARCELNO   -5.729e-08   2.63e-09    -21.794      0.000   -6.24e-08   -5.21e-08
WATER_DIST    -1.3618      0.259     -5.259      0.000      -1.869      -0.854
LandLength    20.3050      0.481     42.194      0.000      19.362      21.248
RAIL_DIST      1.1197      0.490      2.285      0.022       0.159       2.081
==============================================================================
Omnibus:                     5832.835   Durbin-Watson:                   1.994
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            71376.279
Skew:                           2.682   Prob(JB):                         0.00
Kurtosis:                      15.120   Cond. No.                     7.36e+12
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.36e+12. This might indicate that there are
strong multicollinearity or other numerical problems.