## **Practice Exercise - 04**

### Fitting a Simple Linear Regression Model Using the Statsmodels formula API
Practice this exercise according to the instructions given in description:

### Import necessary Modules:

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

### Loading Data

In [ ]:
Housing_data = pd.read_csv\
('https://raw.githubusercontent.com/fenago/DSBook/main/Chapter%202/Housing.csv')

# Write code to display first five entries:

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [ ]:
#Inspecting the data types of the columns

<class 'pandas.core.frame.DataFrame'>
Int64Index: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 59.6+ KB

### Define a linear regression model and store it in a variable:

### Call the .fit() method of the model instance and assign the results of the method to a variable,

### Finally, Print the summary stored in Model - Regression analysis results
Your output should  be consistent with the given output

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.293
Model:                            OLS   Adj. R-squared:                  0.291
Method:                 Least Squares   F-statistic:                     156.8
Date:                Sun, 13 Mar 2022   Prob (F-statistic):           2.40e-30
Time:                        08:50:00   Log-Likelihood:                -5989.5
No. Observations:                 381   AIC:                         1.198e+04
Df Residuals:                     379   BIC:                         1.199e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   2.208e+06   2.23e+05      9.890      0.000    1.77e+06    2.65e+06
area         512.0824     40.893     12.523      0.000     431.677     592.488
==============================================================================
Omnibus:                       65.360   Durbin-Watson:                   2.068
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              117.943
Skew:                           0.969   Prob(JB):                     2.45e-26
Kurtosis:                       4.917   Cond. No.                     1.46e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.46e+04. This might indicate that there are
strong multicollinearity or other numerical problems.