## **Exercise 3.03:**
### Feature Engineering â€“ Exploration of Individual Features

  ### Importing modules

In [1]:
import pandas as pd

### Loading Data

In [2]:
notes_data = pd.read_csv\
('https://raw.githubusercontent.com/fenago/datasets/main/BankNote_Authentication.csv')
#-------Type code here to display first five entries from daatset ------#


#------Solution------#
notes_data.head()

   variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

### Finding a relationship between curtosis and the class for notes

In [4]:
# Relationship between skewness and authentication of note 
notes_data.groupby(['curtosis', 'class'])['class']\
        .agg(CurtosisToT='count').reset_index()

      curtosis  class  CurtosisToT
0      -5.2861      1            1
1      -5.2613      1            1
2      -5.2159      1            1
3      -5.2133      1            1
4      -5.1508      1            1
...        ...    ...          ...
1300   17.5795      1            1
1301   17.5932      1            1
1302   17.6052      1            1
1303   17.6772      1            1
1304   17.9274      1            1

[1305 rows x 3 columns]

In [5]:
"""
Relationship between ENTROPY and Authentication"Class"
"""
notes_data.groupby(['entropy', 'class'])['class']\
        .agg(entropyToT='count').reset_index()

      entropy  class  entropyToT
0     -8.5482      0           1
1     -7.8719      0           1
2     -7.7853      0           1
3     -7.7581      0           1
4     -7.6612      0           1
...       ...    ...         ...
1242   2.0862      0           1
1243   2.1353      1           1
1244   2.1547      0           1
1245   2.1625      0           1
1246   2.4495      0           1

[1247 rows x 3 columns]

### Taking the quantiles for 25%, 50% and 75% of the variance data

In [9]:
#Write your code here



# ---Solution ---#
#import numpy as np
#np.quantile(notes_data['variance'],[0.25,0.5,0.75])

array([-1.773   ,  0.49618 ,  2.821475])

###  Converting the numerical values of  into categorical values

In [10]:
notes_data['VarianceClass'] = 'Quant1'
notes_data.loc[(notes_data['variance'] > -1.773) \
              & (notes_data['variance'] < 0.49618), \
              'VarianceClass'] = 'Quant2'
notes_data.loc[(notes_data['variance'] > 0.49618) \
              & (notes_data['variance'] < 2.821475), \
              'VarianceClass'] = 'Quant3'
notes_data.loc[notes_data['variance'] > 1428, \
             'VarianceClass'] = 'Quant4'
notes_data.head()

   variance  skewness  curtosis  entropy  class VarianceClass
0   3.62160    8.6661   -2.8073 -0.44699      0        Quant1
1   4.54590    8.1674   -2.4586 -1.46210      0        Quant1
2   3.86600   -2.6383    1.9242  0.10645      0        Quant1
3   3.45660    9.5228   -4.0112 -3.59440      0        Quant1
4   0.32924   -4.4552    4.5718 -0.98880      0        Quant2

### Calculating the Variance under each quantile

In [11]:

VarianceToT = notes_data.groupby(['VarianceClass'])['class']\
                     .agg(VarianceToT='count').reset_index()
VarianceToT

  VarianceClass  VarianceToT
0        Quant1          686
1        Quant2          343
2        Quant3          343

### Calculating the total Variance Class categorised as per quantile

In [12]:
# Type your code:



# ----Solution ----#
#VarianceEst = notes_data.groupby(['VarianceClass', 'class'])['class']\
#                      .agg(VarianceC='count').reset_index()
#VarianceEst

  VarianceClass  class  VarianceC
0        Quant1      0        377
1        Quant1      1        309
2        Quant2      0        111
3        Quant2      1        232
4        Quant3      0        274
5        Quant3      1         69

### Merge both data frames

In [13]:
# Merging both the data frames
VarianceComb = pd.merge(VarianceEst, VarianceToT, \
                       on = ['VarianceClass'])
VarianceComb['Var'] = (VarianceComb.VarianceC \
                          / VarianceComb.VarianceToT)*100
VarianceComb

  VarianceClass  class  VarianceC  VarianceToT        Var
0        Quant1      0        377          686  54.956268
1        Quant1      1        309          686  45.043732
2        Quant2      0        111          343  32.361516
3        Quant2      1        232          343  67.638484
4        Quant3      0        274          343  79.883382
5        Quant3      1         69          343  20.116618